from typing import Protocol
import torch

class BoxedModel(Protocol):
    n_tokens: int

    def set_repeg(self, enabled: bool = True) -> None: ...
    def reset(self) -> None: ...
    def step(self, token: int) -> None: ...
    def predict(self) -> torch.Tensor: ...